# Generated by Django 4.2.5 on 2025-04-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='endereco',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
    ]
