# Generated by Django 4.2.5 on 2025-04-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0003_alter_client_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
