# Generated by Django 4.2.5 on 2025-04-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0004_alter_client_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='endereco',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
